/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uit.ensak.scraping;

import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Fighter
 */
public class StartScrap extends javax.swing.JFrame {

    /**
     * Creates new form StartScrap
     */
    public StartScrap() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        PieNivEtud pie1=null;
        try {
            pie1 = new PieNivEtud();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanel2.add(pie1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(510, 0, 490, 390);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        PieContrat pie=null;
        try {
            pie = new PieContrat();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainPanel.add(pie);

        jPanel1.add(mainPanel);
        mainPanel.setBounds(0, 0, 500, 390);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        try {
            // TODO add your handling code here:
            BarChart bar=null;

            bar =new BarChart();
            bar.barchart();

            jPanel3.add(bar);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        }

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 390, 980, 430);

        jMenu1.setText("Reload");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Scrap/JSoup");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Scrap/Selenium");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Purge DB");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Clean DB");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("EntrepriseOffers");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu7.setText("ML Algorithms");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });

        jMenuItem3.setText("Algo 1");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuItem4.setText("Algo 2");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
         
      
    
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
     



// TODO add your handling code here:
        try {
            new Scraping().vmain();
            new Notifications().operationOK();
        } catch (IOException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
            new Notifications().operationKO();
        }

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
       // TODO add your handling code here:
        //jMenu2.setForeground(Color.red);// couleur du text
       //jMenu2.setBackground(Color.CYAN);// couleur d'arriere plan
       
        
       //jMenu2.setEnabled(false);
       
        try {
            new Scraping().vmain();
            new Notifications().operationOK();
        } catch (IOException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
            new Notifications().operationKO();
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
//       jMenu4.setForeground(Color.red);// couleur du text
//       jMenu4.setBackground(Color.CYAN);// couleur d'arriere plan
//       jMenu4.setEnabled(false);
        try {
            //étape 1: charger la classe driver
            Class.forName("org.postgresql.Driver");
            
            //étape 2: créer l'objet de connexion
            
            
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost/scraping", "postgres", "admin");
            PreparedStatement pst = null;
            
            
            
            Statement stmt = conn.createStatement();
            
            
            String stm = "delete from jsoup;";
            pst = conn.prepareStatement(stm);
            pst.executeUpdate();
       
            conn.close();
            new Notifications().operationOK();
        } catch (ClassNotFoundException | SQLException ex) {
            new Notifications().operationKO();
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
try {
            //étape 1: charger la classe driver
            Class.forName("org.postgresql.Driver");
            
            //étape 2: créer l'objet de connexion
            
            
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost/scraping", "postgres", "admin");
            PreparedStatement pst = null;
            
            
            
            Statement stmt = conn.createStatement();
            String stm = "delete from jsoup;";
            pst = conn.prepareStatement(stm);
            pst.executeUpdate();
            
            
            PreparedStatement pst1 = null;
            Statement stmt1 = conn.createStatement();
            String stm1 = "delete from jsoup1;";
            pst1 = conn.prepareStatement(stm1);
            pst1.executeUpdate();
            
            
            conn.close();
            new Notifications().operationOK();
        } catch (ClassNotFoundException | SQLException ex) {
            new Notifications().operationKO();
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
         try {
             System.out.println("Ok");
            //étape 1: charger la classe driver
            Class.forName("org.postgresql.Driver");
            
            //étape 2: créer l'objet de connexion
            
            
            Connection conn3 = DriverManager.getConnection("jdbc:postgresql://localhost/scraping", "postgres", "admin");
            PreparedStatement pst3 = null;
            Statement stmt3 = conn3.createStatement();
            String stm3 = "UPDATE public.jsoup SET nbr_post='NA' WHERE nbr_post like '%/%/%';";
            pst3 = conn3.prepareStatement(stm3);
            pst3.executeUpdate();
            conn3.close();
            
            new Notifications().operationOK();
        } catch (ClassNotFoundException | SQLException ex) {
            new Notifications().operationKO();
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        try {
             System.out.println("Ok");
            //étape 1: charger la classe driver
            Class.forName("org.postgresql.Driver");
            
            //étape 2: créer l'objet de connexion
            
            ////////////////////
        
            
        
        ///////////////////
            
            
            Connection conn3 = DriverManager.getConnection("jdbc:postgresql://localhost/scraping", "postgres", "admin");
            PreparedStatement pst3 = null;
            Statement stmt3 = conn3.createStatement();
            String stm3 = "UPDATE public.jsoup SET nbr_post='NA' WHERE nbr_post like '%/%/%';";
            pst3 = conn3.prepareStatement(stm3);
            pst3.executeUpdate();
             
            System.out.println("1");
            Connection conn31 = DriverManager.getConnection("jdbc:postgresql://localhost/scraping", "postgres", "admin");
            PreparedStatement pst31 = null;
            Statement stmt31 = conn31.createStatement();
            System.out.println("2");
            String stm31 = "UPDATE public.jsoup1 SET nbr_post='NA' WHERE nbr_post like '%/%/%';";
            pst31 = conn31.prepareStatement(stm31);
            System.out.println("3");
            pst31.executeUpdate();
            System.out.println("4");
            
                        
            
            System.out.println("OK1"); 
            Connection conn4 = DriverManager.getConnection("jdbc:postgresql://localhost/scraping", "postgres", "admin");
           // Statement stmt4 = conn4.createStatement();
            PreparedStatement pst4 = null;
            String stm4 = "UPDATE public.jsoup SET addresse='NA' WHERE addresse like '';";
            pst4 = conn4.prepareStatement(stm4);
            pst4.executeUpdate();
            
            //Statement stmt41 = conn4.createStatement();
            PreparedStatement pst41 = null;
            String stm41 = "UPDATE public.jsoup1 SET addresse='NA' WHERE addresse in('','-','--','---');";
            pst41 = conn4.prepareStatement(stm41);
            pst41.executeUpdate();
            
            //Connection conn5 = DriverManager.getConnection("jdbc:postgresql://localhost/scraping", "postgres", "admin");
            Statement stmt5 = conn4.createStatement();
            PreparedStatement pst5 = null;
            String stm5 = "UPDATE public.jsoup	SET region= substr(region,16,40) WHERE substr(region,1,1) in ('1','2','3','4','5','6','7','8','9','0');";
            pst5 = conn4.prepareStatement(stm5);
            pst5.executeUpdate();
            
            Statement stmt521 = conn4.createStatement();
            PreparedStatement pst521 = null;
            String stm521 = "update jsoup set region= trim(region);";
            pst521 = conn4.prepareStatement(stm521);
            pst521.executeUpdate();
            
            Statement stmt51 = conn4.createStatement();
            PreparedStatement pst51 = null;
            String stm51 = "UPDATE public.jsoup1 SET region= substr(region,16,40) WHERE substr(region,1,1) in ('1','2','3','4','5','6','7','8','9','0');";
            pst51 = conn4.prepareStatement(stm51);
            pst51.executeUpdate();
            
            Statement stmt52 = conn4.createStatement();
            PreparedStatement pst52 = null;
            String stm52 = "update jsoup1 set region= trim(region);";
            pst52 = conn4.prepareStatement(stm52);
            pst52.executeUpdate();
            
            Statement stmt523 = conn4.createStatement();
            PreparedStatement pst523 = null;
            String stm523 = "update jsoup1 set region= substr(region,3) where region like('_ %');";
            pst523 = conn4.prepareStatement(stm523);
            pst523.executeUpdate();
            
            //Connection conn6 = DriverManager.getConnection("jdbc:postgresql://localhost/scraping", "postgres", "admin");
            Statement stmt6 = conn4.createStatement();
            PreparedStatement pst6 = null;
            String stm6 = "UPDATE public.jsoup SET region= substr(region,3,40) WHERE substr(region,1,1) in ('r');";
            pst6 = conn4.prepareStatement(stm6);
            pst6.executeUpdate();
       System.out.println("OK2");
       conn3.close();
            conn4.close();
            new Notifications().operationOK();
        } catch (ClassNotFoundException | SQLException ex) {
            new Notifications().operationKO();
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    dispose();   
       //NewWindow myWindow = new NewWindow();        
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
       dispose(); 
       StartScrap startscrap= new StartScrap();
       startscrap.setVisible(true);
       startscrap.setLocationRelativeTo(null);
        

    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        //dispose(); 
       EntrepChart entrepChart= new EntrepChart();
       entrepChart.setVisible(true);
       entrepChart.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            new Cluster().mainML();         // TODO add your handling code here:
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        try {
            new Cluster().mainML();         // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(StartScrap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new Clustering().mainCluster();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
new Clustering().mainCluster();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        try {
         //   Scrapper scrapper = new Scrapper();
      // scrapper.scrapper();     
            
        } catch (Exception e) {
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
      // TODO add your handling code here:
        try {
           // Scrapper scrapper = new Scrapper();
      // scrapper.scrapper();     
            
        } catch (Exception e) {
        }
 
         
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               StartScrap startscrap= new StartScrap();
               startscrap.setVisible(true);
                startscrap.setLocationRelativeTo(null);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
